sudo: true

install:
- sudo apt-get update
- sudo apt-get install -y apt-transport-https ca-certificates
- sudo bash -c 'echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list'
- sudo bash -c 'curl -sL https://www.dotdeb.org/dotdeb.gpg | apt-key --keyring /etc/apt/trusted.gpg.d/docker-keyring.gpg add -'
- sudo apt-get update
- sudo apt-get install -y lxc-docker

script:
- docker build -t rentabiliweb/phpunit .
