sudo: true

install:
- sudo apt-get update
- sudo apt-get install -y apt-transport-https ca-certificates
- sudo bash -c 'echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list'
- sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
- sudo apt-get update
- sudo apt-get install -y lxc-docker

script:
- bash -c 'echo OK'
